# Generated by Django 6.0 on 2026-01-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ful_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=13)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.EmailField(max_length=45)),
            ],
        ),
    ]
