# Generated by Django 6.0 on 2026-01-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsignup',
            old_name='Ful_name',
            new_name='full_name',
        ),
    ]
