# Generated by Django 6.0 on 2026-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ful_name_doctorsignup_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.EmailField(max_length=45)),
                ('Confirm_password', models.EmailField(max_length=45)),
            ],
        ),
    ]
