# Generated by Django 6.0 on 2026-01-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patientsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsignup',
            name='Confirm_password',
        ),
        migrations.AlterField(
            model_name='patientsignup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
